/*License Notification
Fab@Home operates under the BSD Open Source License

Copyright (c) 2006, Hod Lipson and Evan Malone (evan.malone@cornell.edu) All rights reserved. 

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met: 

Redistributions of source code must retain the above copyright notice, 
this list of conditions and the following disclaimer. 
Redistributions in binary form must reproduce the above copyright notice, 
this list of conditions and the following disclaimer in the documentation and/or 
other materials provided with the distribution. 
Neither the name of the Fab@Home Project nor the names of its contributors may be 
used to endorse or promote products derived from this software without specific 
prior written permission. 

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

//Parameters header file for the Fab@Home System

//specify required firmware version
#define NEEDS_FW_VERSION 3

//set the (max) number of axes in the system
#define AXES_CNT 6
#define POSITION_AXES 3	//how many axes of positioning? Tool axes are from POSITION_AXES through AXES_CNT-1

//tell the uC which axes/directions have HW limit switches
//for now, only X,Y,Z limits are supported in firmware
#define X_FWD_HW_LIM TRUE
#define X_BKD_HW_LIM TRUE
#define Y_FWD_HW_LIM TRUE
#define Y_BKD_HW_LIM TRUE
#define Z_FWD_HW_LIM TRUE
#define Z_BKD_HW_LIM TRUE
#define U_FWD_HW_LIM FALSE  //no firmware support yet
#define U_BKD_HW_LIM TRUE	
#define V_FWD_HW_LIM FALSE	//no firmware support yet
#define V_BKD_HW_LIM TRUE
#define W_FWD_HW_LIM FALSE	//no firmware support yet
#define W_BKD_HW_LIM FALSE	

#define MAX_PACKET 128 //max packet is 64 bytes for USB VCOM
//Max step rate for any of the controlled axes
//assumes timer1 prescale is set so that timer1 counts at 1MHz.
#define MAX_STEP_FREQ 11400 //measured max step rate generated by microcontroller (as of Firmware v.3, 4/27/07)
#define OLD_MSPS 5000	//held over from earlier versions to preserve pushout,suckback parameters of tool files
//define default jog increment sizes for axes/tools
#define JOG_STEP_AXIS 0.5
#define MAX_JOG_STEP_AXIS 10
#define JOG_STEP_TOOL 0.1
#define MAX_JOG_STEP_TOOL 10
#define DEFAULT_TRAVEL_CLEARANCE 3 //clearance between tip and last layer when traversing

#define MIN_Q_TRANSFER 10			//require at least this much space in the queue before sending more data
#define STATUS_UPDATE_PERIOD 25	//ms delay in fetching status from printer
#define VIEW_REFRESH_MULT 5	// how many status updates between view refreshes
#define MAX_VIEW_REFRESH_PERIOD 500 //maximum period allowed for view refresh (to prevent bogging down too much)
#define MAX_STATUS_UPDATE_PERIOD 250 //maximum period allowed for status update
#define COMMS_AVE_WINDOW 100 //number of periods to average comms performance over
#define COMMS_RERATE_THRESH 0.01 //comms error rate at which rate will be increased
#define COMMS_DERATE_THRESH 0.10 //comms error rate (errors/total sent) at which rate will be slowed
#define COMMS_FATAL_THRESH 0.99 //comms error rate at which comms will be considered dead
#define COMMS_P_GAIN	10	//proportional gain for managing comms update rate
#define AMP_IDLE_DISABLE_TIME 60 //disable amps if idle for this many seconds

#define MAX_PARTFILE_SELECT	20	//max number of part files a user can import at once
#define MAN_TC_TIME	300	//estimated time (s) for manual tool change
#define	AUTO_TC_TIME 10	//estimated time (s) for auto (multi-tool) tool change

#define VIEW_REFRESH_TIMER 1
#define JOG_CARRIAGE_DLG_TIMER 2
#define JOG_TOOL_DLG_TIMER 3

#define TIMEOUT_ITER 10
#define EMULATOR_SLOWDOWN 1	//determines speed of emulator
#define SLEEP_PERIOD 100	//Sleep time for WaitForMoveDone and WaitForMoveStart (ms)

#define CONSOLIDATION_FACTOR 3.0 //within a given contour, paths whose endpoints are closer than pathwidth*CONSOLIDATION_FACTOR will be joined
#define AVERAGE 5 //FindHomePos() and FindSafePos() number of times the final movement is repeated and averaged for error minimization