//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FabAtHome.rc
//
#define IDD_ABOUTBOX                    100
#define ID_FABRICATION_STATUS           101
#define IDD_TOOLDLGPARAMETERS           103
#define IDD_PRINTERDLGGENERAL           104
#define IDD_PRINTERDLGCOMPONENT         105
#define IDD_LOGBAR                      123
#define IDR_MAINFRAME                   128
#define IDR_FabAtHomeTYPE               129
#define IDD_PROGRESSDLG                 131
#define IDD_AXES                        133
#define IDD_JOGCARRIAGE                 134
#define IDC_HANDCURSOR                  135
#define IDD_JOGTOOL                     135
#define IDD_CHUNKDLG                    136
#define IDD_COMPORT                     137
#define IDD_STATUSDLG                   138
#define IDD_BUILDINFO                   139
#define IDR_ACCELERATOR1                142
#define IDD_TOOLCHANGE                  143
#define IDB_FAHLOGO                     145
#define IDB_CCSLLOGO                    146
#define IDB_LOGOCENPRA                  149
#define IDC_BAR                         1000
#define IDC_TEXT                        1001
#define IDC_XAX                         1007
#define IDC_YAX                         1008
#define IDC_TOOLLIST                    1008
#define IDC_ZAX                         1009
#define IDC_DESCRIPTION                 1009
#define IDC_XEDIT                       1010
#define IDC_SPINX                       1011
#define IDC_YEDIT                       1012
#define IDC_SPINY                       1013
#define IDC_ZEDIT                       1014
#define IDC_SPINZ                       1015
#define IDC_BUTTONHOME                  1018
#define IDC_BUTTONSAFE                  1019
#define IDC_BUTTONSETHOME               1019
#define IDC_BUTTONORIGIN                1020
#define IDC_BUTTONGOTOORIGIN            1020
#define IDC_RADIO1                      1021
#define IDC_RADIOSET                    1021
#define IDC_BUTTONSETORIGIN             1021
#define IDC_RADIOMOVE                   1022
#define IDC_BUTTONGOTOSAFE              1022
#define IDC_BUTTONSETSAFE               1023
#define IDC_COMBOTOOL                   1024
#define IDC_EDITPOS                     1025
#define IDC_SPINPOS                     1026
#define IDC_TOOL_INC                    1027
#define IDC_BUTTONUNLOAD                1029
#define IDC_BUTTONBOTTOM                1030
#define IDC_RADIOMOV                    1031
#define IDC_COLOR                       1034
#define IDC_COMBOBOXEX1                 1036
#define IDC_COMBOMAT                    1037
#define IDC_BUTTONCOLOR                 1039
#define IDC_EDITALPHA                   1041
#define IDC_STATICMAT                   1044
#define IDC_STATICTOOL                  1045
#define IDC_COMBO_PORT                  1046
#define IDC_EDIT_XRT                    1047
#define IDC_EDIT_YRT                    1048
#define IDC_EDIT_RTPOS                  1048
#define IDC_EDIT3                       1049
#define IDC_EDIT_ZRT                    1049
#define IDC_STATUSTEXT                  1049
#define IDC_BUILDTEXT                   1050
#define IDC_STATICBUILD                 1051
#define IDC_X_INC                       1052
#define IDC_Y_INC                       1053
#define IDC_AXES_STATIC                 1053
#define IDC_Z_INC                       1054
#define IDC_BUILDINFOTEXT               1054
#define IDC_COMBOPRIORITY               1055
#define IDC_CHECK_CURRENT               1056
#define IDC_LIST_AVAIL                  1058
#define IDC_LIST_MOUNTED                1059
#define IDC_BUTTON_MOUNT                1060
#define IDC_BUTTON_DISMOUNT             1061
#define IDC_BUTTON_UNMOUNT              1061
#define IDC_MAXTOOLS                    1062
#define IDC_STATIC_FAHLOGO              1066
#define IDC_STATIC_CCSLLOGO             1067
#define IDC_COMBO_CHUNKNAME             1068
#define IDC_CHECK_BOUNDFIRST            1069
#define IDC_TIPDIAM                     1070
#define IDC_STATIC_LOGOCENPRA           1070
#define IDC_PATHWIDTH                   1071
#define IDC_Name                        1071
#define IDC_SUCKBACK                    1072
#define IDC_LIMIT_SWITCH                1072
#define IDC_PATHHEIGHT                  1073
#define IDC_COMPONENT                   1073
#define IDC_PUSHOUT                     1074
#define IDC_JOGSPEED                    1074
#define IDC_OFFSET                      1074
#define IDC_STATUS_UPDATE_PERIOD        1076
#define IDC_DEFAULT_POD                 1077
#define IDC_APPENDGEOM                  1078
#define IDC_TOOLLIMITSWITCH             1078
#define IDC_SUCKBACKDELAY               1085
#define IDC_DEPOSITIONRATE              1086
#define IDC_PAUSEPATHS                  1087
#define IDC_CLEARANCE                   1088
#define IDC_PATHSPEED                   1089
#define IDC_TOOLGEOM                    1095
#define IDC_TOOLOFFSET                  1096
#define IDC_BARRELOFFSET                1097
#define IDC_TOOLCOLOR                   1098
#define IDC_BARRELGEOM                  1099
#define IDC_BARRELDIAM                  1100
#define IDC_BARRELCOLOR                 1101
#define IDC_TIPGEOM                     1112
#define IDC_TIPOFFSET                   1113
#define IDC_PLUNGERGEOM                 1114
#define IDC_TIPCOLOR                    1115
#define IDC_TIPPOINT                    1116
#define IDC_PLUNGERCOLOR                1117
#define IDC_PLUNGEROFFSET               1118
#define IDC_DIRECTION                   1119
#define IDC_VOLUME                      1120
#define IDC_BACKFILL                    1121
#define IDC_MOTOR                       1122
#define IDC_RANGE                       1123
#define IDC_SUCKBACK7                   1124
#define IDC_INCREMENT                   1124
#define IDC_LIMITSWITCH                 1125
#define IDC_MINPATHLENGTH               1125
#define ID_CHUNK_IMPORTGEOMETRY         32772
#define ID_VIEW_SHADED                  32773
#define ID_VIEW_ZOOMIN                  32779
#define ID_VIEW_ZOOMOUT                 32780
#define ID_FABRICATE_SIMULATEONLY       32789
#define ID_FABRICATE_CALIBRATE          32791
#define ID_PROCESS_SLICE                32793
#define ID_VIEW_NEXTPATH                32799
#define ID_VIEW_PREVIOUSPATH            32800
#define ID_VIEW_ALLPATHS                32801
#define ID_VIEW_SHOWPATHS               32802
#define ID_VIEW_SHOWMODEL               32803
#define ID_PROCESS_SLICECURVED          32804
#define ID_MODEL_MATERIAL               32806
#define ID_MODEL_CHECKCOLLISIONS        32807
#define ID_VIEW_SHOWTOOL                32808
#define ID_PROCESS_SHOWERRORS           32809
#define ID_FABRICATE_FABRICATE          32810
#define ID_FABRICATE_PAUSE              32811
#define ID_MODEL_DELETE                 32812
#define ID_VIEW_PATHNORMALS             32813
#define ID_VIEW_MODELNORMALS            32815
#define ID_MODEL_MOVETOORIGIN           32816
#define ID_EDIT_SELECTALL               32817
#define ID_MODEL_TRANSLATE              32818
#define ID_MODEL_ROTATE                 32819
#define ID_MODEL_SCALE                  32820
#define ID_PRINTER_LOADCONFIGURATION    32821
#define ID_PRINTER_JOG                  32822
#define ID_PRINTER_JOGTOOL              32823
#define ID_MODEL_PROPERTIES             32824
#define ID_PRINTER_INITIALIZEHARDWARE   32825
#define ID_PRINTER_EMULATEHARDWARE      32826
#define ID_FABRICATION_SLICE            32831
#define ID_VIEW_TRACETOOL               32832
#define ID_VIEW_TOOLTRACES              32833
#define ID_VIEW_SHOWTOOLTRACES          32834
#define ID_VIEW_SHOWTIPTRACES           32835
#define ID_VIEW_SHOWSTATUS              32836
#define ID_PRINTER_ENABLEMOTION         32837
#define ID_PRINTER_PAUSEQUEUE           32838
#define ID_PRINTER_ABORTALLMOTION       32839
#define ID_PRINTER_RESETHARDWARE        32840
#define ID_VIEW_SHOWCOMMANDED           32841
#define ID_PRINTER_SHOWSTATUS           32842
#define ID_VIEW_LAYERS                  32843
#define ID_LAYERS_L                     32844
#define ID_JOG_X_FWD                    32849
#define ID_JOG_X_BKD                    32850
#define ID_JOG_Y_LEFT                   32851
#define ID_JOG_Y_RIGHT                  32852
#define ID_JOG_Z_UP                     32853
#define ID_JOG_Z_DOWN                   32854
#define ID_JOG_TOOL_FWD                 32857
#define ID_JOG_TOOL_BKD                 32858
#define ID_FABRICATION_PAUSEPRINTING    32862
#define ID_BUTTONSTOP                   32863
#define ID_VIEW_CURRENTPATH             32866
#define ID_VIEW_RESETVIEW               32872
#define ID_TOOL_LOADFILES               32874
#define ID_TOOL_REFRESHPARAMETERS       32875
#define ID_VIEW_SHOWBUILDINFO           32876
#define ID_TOOL_CHANGETOOLS             32877
#define ID_FABRICATION_PAUSEATTOOLCHANGE 32878
#define ID_PRINTER_EMERGENCYSTOP        32880
#define ID_FABRICATION_AUTORESUMEFROMAUTOPAUSE 32883
#define ID_FABRICATION_AUTORESUME       32884
#define ID_PRINTER_LOGMOTION            32885
#define ID_PRINTER_LOG                  32886
#define ID_VIEW_LOGBAR                  32887
#define ID_VIEW_LOGWINDOW               32888
#define ID_TOOL_TOOLCONFIGURATION       32889
#define ID_FABRICATION_RASTERFIRST      32890
#define ID_FABRICATION_FILLFIRST        32891
#define ID_PRINTER_EMULATEFASTER        32892
#define ID_PRINTER_EMULATESLOWER        32893
#define ID_EMULATION_EMULATEHARDWARE    32894
#define ID_VIEW_RENDERSHADED            32895
#define ID_VIEW_SHOWPRINTER             32896
#define ID_VIEW_SHOWTRACE               32897
#define ID_PRINTER_NETWORKCONNECT       32898
#define ID_TOOLDLGTITLE                 57682
#define ID_PRINTERDLGTITLE              57683

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32899
#define _APS_NEXT_CONTROL_VALUE         1075
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
